-- =============================================================================
-- Effect-enricher schema extension — adds 'effect_updated' to scm_write_log's
-- operation CHECK constraint so the QuantitativeEffectEnricher daemon can
-- emit the audit event. Idempotent — drops + re-adds the constraint each run.
-- =============================================================================

-- Drop the existing CHECK (name generated by Postgres at table creation; we
-- target it by using a generic name pattern that we set below).
ALTER TABLE erik_ops.scm_write_log
    DROP CONSTRAINT IF EXISTS scm_write_log_operation_check;

-- Recreate with 'effect_updated' added.
ALTER TABLE erik_ops.scm_write_log
    ADD CONSTRAINT scm_write_log_operation_check
    CHECK (operation IN (
        'edge_created',
        'edge_superseded',
        'edge_invalidated',
        'cf_computed',
        'bootstrap_progress',
        'reverification_run',
        'intervention_flagged',
        'intervention_unflagged',
        'effect_updated'
    ));
